### ISSUE TITLE
后期是否可以支持预览其它类型的文件，例如视频、word

### ISSUE THREAD

**Issue by 1067237855** [windingwind/zotero-pdf-preview#10]
后期是否可以支持预览其它类型的文件，例如视频（文献supporting经常会有视频资料）、word等等，类似quicklook

**Comment by windingwind** [comment]
word预计不会支持，视频可以

**Comment by 1067237855** [comment]
> 

点赞！！！期待！！！

**Comment by 1067237855** [comment]
> word预计不会支持，视频可以

还有一个建议，希望可以出一个类似obsidian的custom frames功能的插件

**Comment by windingwind** [comment]
侧边栏太小了吧，没法容纳网页？

**Comment by 1067237855** [comment]
> 侧边栏太小了吧，没法容纳网页？

不一定要在侧边栏，关键是能否实现该功能
如果可以实现，那么就可以嵌入各种好用的工具，例如**RSS订阅**网站、notion网页笔记、x-mol文献平台、微信读书网页版、网页版思维导图等等一些快速便捷的工具

**Comment by windingwind** [comment]
可以单独窗口也可以在标签页打开，和浏览器没啥区别。甚至可以做一个搜索框之类的。但关键的问题是，好像直接用浏览器打开也可以做到这些

**Comment by 1067237855** [comment]
custom frames跟浏览器的区别在于，这是一个自定义工具集，zotero安装之后就能获得各种功能拓展实现all in one。功能肯定没法完全跟浏览器比，但一些好用的在线工具利用custom嵌入zotero之后会有很大的差别，例如RSS订阅网站可以替代zotero自带的RSS功能、notion网页笔记替代zotero自带的笔记功能、x-mol文献平台使zotero获得文献速览功能、Todoist待办事项使zotero获得一些速记功能、在线思维导图功能等等，一个custom frames插件就能使zotero**快速获得**各种扩展功能。如果是用浏览器的话就会有很强的割裂感（或者说是操作繁琐），因为是在两个软件里。就好比大佬您开发的翻译插件一样，大家之所以觉得比外置的翻译软件好用，其中一个很重要的原因就是因为他是集成在zotero里面的，单独的翻译软件跟zotero配合会有很强的割裂感，同样地，“直接用浏览器打开”也是一样的道理。

> 可以单独窗口也可以在标签页打开，和浏览器没啥区别。甚至可以做一个搜索框之类的。但关键的问题是，好像直接用浏览器打开也可以做到这些

**Comment by windingwind** [comment]
zotero的标签页目前只能单独切换，左右分屏只能通过新窗口打开实现，打开了新标签页中的网页后仍然要频繁切换标签页。如果能够以某种方式解决，可能会更有实际价值。是否有建议？

**Comment by 1067237855** [comment]
![image](https://user-images.githubusercontent.com/104330036/183346291-42a6adbe-d4e4-4741-86cd-137a649157f8.png)


> zotero的标签页目前只能单独切换，左右分屏只能通过新窗口打开实现，打开了新标签页中的网页后仍然要频繁切换标签页。如果能够以某种方式解决，可能会更有实际价值。是否有建议？

**Comment by tangjyan** [comment]
> ![image](https://user-images.githubusercontent.com/104330036/183346291-42a6adbe-d4e4-4741-86cd-137a649157f8.png)
> 
> > zotero的标签页目前只能单独切换，左右分屏只能通过新窗口打开实现，打开了新标签页中的网页后仍然要频繁切换标签页。如果能够以某种方式解决，可能会更有实际价值。是否有建议？

这个想法太好了

**Comment by 1067237855** [comment]
> > ![image](https://user-images.githubusercontent.com/104330036/183346291-42a6adbe-d4e4-4741-86cd-137a649157f8.png)
> > > zotero的标签页目前只能单独切换，左右分屏只能通过新窗口打开实现，打开了新标签页中的网页后仍然要频繁切换标签页。如果能够以某种方式解决，可能会更有实际价值。是否有建议？
> 
> 这个想法太好了

只是个初步想法，如果大佬能开发出来，还是得看看大家的具体需求和实际使用体验

**Comment by windingwind** [comment]
是的，功能上肯定可以实现，主要问题是我没啥时间，维护就够忙的了

**Comment by 1067237855** [comment]
> 

大佬搞几个收费的插件吧，青柠copy别人的想法却在收费，大佬做了那么多原创的插件也该让大家支持一下了

**Comment by windingwind** [comment]
初心是让大家方便，收费就失去意义了，我觉得获取知识的工具尽可能还是不要有门槛。

我其实在github放了赞助链接，点进去也有国内的付款方式，不过不靠这个赚钱，不会主动引导大家赞助。国内许多用户都是学生，本来没有啥收入，几十块钱买本书看看比赞助我可能更有意义。

如果经济承受得起并且确实觉得我这几个工具有帮助，适当赞助我当然也非常高兴的。

**Comment by 1067237855** [comment]
> 是的，功能上肯定可以实现，主要问题是我没啥时间，维护就够忙的了

![image](https://user-images.githubusercontent.com/104330036/196575560-ef0ee404-d860-4115-8dfb-1a91be7ba7fc.png)

![image](https://user-images.githubusercontent.com/104330036/196575274-1340444c-4af6-42c4-bb77-348bcca008f7.png)


大佬这是开发出来了吗？还是我又卡BUG了

**Comment by windingwind** [comment]
bug吧，但是可以试下能正常使用吗

**Comment by XingyanMao** [comment]
> 

我去，这是啥插件？太强了还能嵌入notion

**Comment by Geo123abc** [comment]
希望老大再考虑一下添加这个功能，原因如下
1. 这样做可以很好地将notion、思源笔记这样的笔记软件和zotero结合起来，思源笔记支持网络伺服的功能，如果添加这个功能，就能把思源笔记“嵌入”到zotero中，达到“管理链接而非管理本体”的效果
2. 添加这个功能后，zotero的扩展性就更好了
3. 文献管理软件citavi、思维导图软件mindmanager也是支持内置浏览器的，应该是有某些方面考虑的
