### ISSUE TITLE
Zotero 7 - PDF-Preview Release 1.0.0-2 - Vertical separation in Info Tab moving down

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-pdf-preview#101]
Thank you for this update fixing the previous issues.
I still see a problem for the Preview in the Info Tab. Everytime I select another item, the horizontal line separating the item metadata from the preview is moving down slightly. It is a small increment, but after a few 10th of items selected, I need to adjust again the vertical position of the separation line.

[PDF-Preview Release 1.0.0-2](https://github.com/windingwind/zotero-pdf-preview/releases/tag/1.0.0-2)
Zotero 7.0.0-beta.22+676f820f8 (64-bit)
Windows 10

**Comment by vancleve** [comment]
I'm seeing this too on macos 13.5 Zotero 7.0.0-beta.28+3a43a98f1 with version [1.0.0-3](https://github.com/windingwind/zotero-pdf-preview/releases/tag/1.0.0-3)

See https://github.com/windingwind/zotero-pdf-preview/issues/108 for a video of the bug.
