### ISSUE TITLE
Zotero 7 - Preview Tab Name not working

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-pdf-preview#102]
I have tried to change the Preview Tab Name and restart Zotero, but it still shows the default "Preview".
I have tested on Windows 10 and Ubuntu 23.04 with Zotero beta 23 (64 bits) and the PDF Preview Release 1.0.0-2.

**Comment by WMAM** [comment]
The same here with release 1.0.0-3, Windows 10, and Zotero 7-beta.32
