### ISSUE TITLE
Zotero 7 - Vertical separation in Info Tab moved to the top at each restart of Zotero

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-pdf-preview#103]
Every time I restart Zotero, the vertical separation between the metadata and the PDF preview in the Info Tab is moved to the top, leaving only the Item Type visible. Even if I move it down to another place and restart, it does not remember the position before restart and goes back to the top.
I have tested on Windows 10 and Ubuntu 23.04 with Zotero beta 23 (64 bits) and the PDF Preview Release 1.0.0-2.

**Comment by vancleve** [comment]
I see this too. It'd be great if it got fixed!
