### ISSUE TITLE
Zotero 7 - Cannot collapse the PDF preview in the Info Tab

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-pdf-preview#106]
If I move down the separation line between the item metadata and the PDF preview to the bottom of the Zotero window, it does not trigger the collapse of the PDF preview pane. If Zotero is in full screen and you go down to the limit of the Zotero window at the bottom, you cannot recover the separation line to move it anymore.

Windows 10
Zotero 7.0.0-beta.23+fb5934563 (64-bit)
PDF Preview Release 1.0.0-2

**Comment by RitaQian-westlake** [comment]
I met the similar problem. It actually cannot work normally in my computer. Once I install, The separation line will be located on very high position but the preview panel just keeps blank without any page view. Sometimes the page view appears, but disappear when I click another item, It may show if I move the separation line up, but the original block area is still blank. The view just looks like taking files out from a folder.

Ubuntu 22.04
Linux 64-bit
PDF Preview Release 1.0.0-2
