### ISSUE TITLE
无法安装插件“%S”。它可能无法与该版本的 Zotero 兼容。

### ISSUE THREAD

**Issue by lalalaquya** [windingwind/zotero-pdf-preview#107]

**Comment by mjthoraval** [comment]
Are you using Zotero 6 or Zotero 7?
For Zotero 6, you should use the Release 0.3.7.
For Zotero 7, you should use the latest Pre-release, Release 1.0.0-2.
https://github.com/windingwind/zotero-pdf-preview/releases

**Comment by kissint8** [comment]
Zotero 6.x will be default selection for mac user. 
Thanks for your replay. It works.
