### ISSUE TITLE
Zotero 7 - moving between items causes preview window in Info pane to resize

### ISSUE THREAD

**Issue by vancleve** [windingwind/zotero-pdf-preview#108]
In version [1.0.0-3](https://github.com/windingwind/zotero-pdf-preview/releases/tag/1.0.0-3), selecting a different item in the item pane causes the preview in the info pane to resize. See video below

https://github.com/windingwind/zotero-pdf-preview/assets/1442334/9282b70d-62a9-430f-973c-f275f5cbefc9

This occurs when the preview is both at the top or bottom of the info panel.

macos 13.5 Zotero 7.0.0-beta.28+3a43a98f1

**Comment by mjthoraval** [comment]
Yes, this was reported here: https://github.com/windingwind/zotero-pdf-preview/issues/101

**Comment by vancleve** [comment]
ah, great, apologies, closing as dup of #101
