### ISSUE TITLE
Zotero 7 -当一个item里面有多个PDF文件时，只能预览第一个PDF

### ISSUE THREAD

**Issue by liut14** [windingwind/zotero-pdf-preview#109]
如题所述

希望可以增加一个切换按钮，在一个item下的不同子项 PDF 之间切换

**Comment by liut14** [comment]
![image](https://github.com/windingwind/zotero-pdf-preview/assets/52646263/2aa08809-d510-4111-a0e2-d32b0a444e9e)
类似这样？

**Comment by XoYaPeng** [comment]
要是有这个功能就更方便了。总是感觉需要打开第二个附件比较麻烦，而且还要展开条目
