### ISSUE TITLE
Zotero 7 - 信息栏的预览高度每次重启会重置

### ISSUE THREAD

**Issue by Saunak626** [windingwind/zotero-pdf-preview#110]
![image](https://github.com/windingwind/zotero-pdf-preview/assets/34276206/c79cd3d7-8e31-429d-9ad1-580f42db513c)
这个信息栏中显示预览的高度每次重启zotero就会重置，且重置之后的高度会占满整个信息栏
<img width="353" alt="image" src="https://github.com/windingwind/zotero-pdf-preview/assets/34276206/3d3bf699-63df-444f-b6f1-812cfe497e06">

**Comment by mjthoraval** [comment]
Same as here: https://github.com/windingwind/zotero-pdf-preview/issues/103
