### ISSUE TITLE
Zotero 7 Beta  29 with updated pdf viewer breaking plugin preview

### ISSUE THREAD

**Issue by danieltomasz** [windingwind/zotero-pdf-preview#113]
See the announcement
https://forums.zotero.org/discussion/106716/available-for-beta-testing-updated-reader-with-epub-snapshot-support-and-new-annotation-types

The PDF code is here https://github.com/zotero/reader

**Comment by vancleve** [comment]
I'm also seeing this.

Also, the location of the preview window seems stuck on the top regardless which of option "top" or "bottom" is selected in the preferences.

**Comment by tendernesses** [comment]
> See the announcement https://forums.zotero.org/discussion/106716/available-for-beta-testing-updated-reader-with-epub-snapshot-support-and-new-annotation-types
> 
> The PDF code is here https://github.com/zotero/reader

bro, what does it mean? do i need to download something to keep the software working?

**Comment by mjthoraval** [comment]
It means that the current code of the PDF Preview plugin is not working with Zotero 7 beta.
The code of the plugin (and maybe of Zotero 7 beta) must be updated before it can work.
So except if you plan to help develop the code, you cannot do anything to get it working in Zotero 7 beta. It simply does not work. Either the original developper or someone else will have to fix the problem in the code before it can be used in Zotero 7 beta.

**Comment by danieltomasz** [comment]
@tendernesses or just download Zotero 6 (stable version), there the older version of the plugin (stable) is working
