### ISSUE TITLE
zotero 7中的 PDF previewer 和 zotero style冲突

### ISSUE THREAD

**Issue by liut14** [windingwind/zotero-pdf-preview#114]
PDF previewer 和 zotero style 都是最新适用于zotero 7的版本
如果开启了 PDF previewer ，那么youjian右键不会显示zotero 定义的其他列，如图所示

![image](https://github.com/windingwind/zotero-pdf-preview/assets/52646263/aaaaf73f-0e37-4f4b-a14b-e4d5466580c0)

**Comment by 11good11** [comment]
我的也是，我把style的列调用出来了，但显示的都是代码

![image](https://github.com/windingwind/zotero-pdf-preview/assets/73817578/86963bc5-4d74-46ec-a3cd-4e5de2a81e3a)
