### ISSUE TITLE
Preview pdf add-on not working, cant preview pdf

### ISSUE THREAD

**Issue by abhishekk79** [windingwind/zotero-pdf-preview#117]
Why is this happening? 

I cant seem to preview pdf, although i have saved pdf for the said references. I have uninstalled and reinstalled, HAVE DISABLED ALL OTHER ADDONS.. Still happens.

I am using Zotero 7 beta.
![Screenshot 2023-08-16 201604](https://github.com/windingwind/zotero-pdf-preview/assets/57443302/65c4d09a-7fca-47a3-95b9-ecb5abe39228)

**Comment by DWCY3574** [comment]
+1
![image](https://github.com/windingwind/zotero-pdf-preview/assets/60478002/96c2ca57-0602-4af7-874b-bccc25f36b45)

**Comment by mjthoraval** [comment]
See here: https://github.com/windingwind/zotero-pdf-preview/issues/113

**Comment by abhishekk79** [comment]
What is the solution??

**Comment by XoYaPeng** [comment]
+1

**Comment by sascharo** [comment]
Same here, running 7.0.0-beta.36+3ef1f0992 (64-bit).

**Comment by xiongfly** [comment]
Same here, running 7.0.0-beta.36+3ef1f0992 (64-bit).

**Comment by 0x127001** [comment]
Same here, running 7.0.0-beta.36+3ef1f0992 (64-bit).

**Comment by 1067237855** [comment]
> Why is this happening?
> 
> I cant seem to preview pdf, although i have saved pdf for the said references. I have uninstalled and reinstalled, HAVE DISABLED ALL OTHER ADDONS.. Still happens.
> 
> I am using Zotero 7 beta. ![Screenshot 2023-08-16 201604](https://user-images.githubusercontent.com/57443302/261046654-65c4d09a-7fca-47a3-95b9-ecb5abe39228.png)


# 无法预览+1：zotero版本 7.0.0-beta.36+3ef1f0992 (64-bit)

**Comment by DWCY3574** [comment]
能先更新一下这个插件吗，translate还能用 @windingwind

**Comment by XoYaPeng** [comment]
感谢大佬！这是福音
