### ISSUE TITLE
可否实现预览到最后一页时继续加载若干页

### ISSUE THREAD

**Issue by tangjyan** [windingwind/zotero-pdf-preview#12]
目前设置中限制只能预览若干页，我想应该是为了考虑性能。但是翻到最后一页说明还有想看的，如果能自动继续加载的话，不知道能不能实现性能和功能的协调平衡。

**Comment by windingwind** [comment]
现在的预览页码方式允许多种、多段设定，因此选择”下一页“将很困难。（例如，用户可以设定预览末5页+前5页，或中间的某几页）。
可通过调整预览限制的设置来自定义预览的页码。将不支持继续加载功能。
