### ISSUE TITLE
无法正常预览7.0.0-beta.38+b79e0b3d7 (64-bit)

### ISSUE THREAD

**Issue by 1067237855** [windingwind/zotero-pdf-preview#120]
无法正常预览
zotero版本：7.0.0-beta.38+b79e0b3d7 (64-bit)
![image](https://github.com/windingwind/zotero-pdf-preview/assets/104330036/015ebcf4-5e37-4770-bf00-533f9c9ee995)

**Comment by wzh4464** [comment]
Same problem on MacOS.

**Comment by wzh4464** [comment]
it works well now! Thank you very much!
