### ISSUE TITLE
Beta4 -PDF preview in  top info pane have additional vertical space 

### ISSUE THREAD

**Issue by danieltomasz** [windingwind/zotero-pdf-preview#121]
Thanks for your work and for the latest  update! I already updated to the last version of the plugin (beta 4).
I'm using Zotero 7.0.0-beta.38+b79e0b3d7 and have the PDF preview set to display 1 page at the top of the item pane, as shown below:
<img width="645" alt="image" src="https://github.com/windingwind/zotero-pdf-preview/assets/7980381/0cd53edc-6a43-452c-97bd-9a72fcbc700d">
However, I'm frequently seeing an empty space under the PDF like this:
![image](https://github.com/windingwind/zotero-pdf-preview/assets/7980381/96cb9ed3-69ff-4a40-b5de-7d120d4eb969)
When I change the preview location setting to bottom (which works fine) and then back to top again, it fixes the issue temporarily. But this behavior repeats after restarting Zotero, so I have to go through the steps of setting it to bottom and then back to top again.

**Comment by mjthoraval** [comment]
It seems to be the same as this one: https://github.com/windingwind/zotero-pdf-preview/issues/103
But with the setting `Preview in Info Tab` `Top` instead of `Bottom`.

**Comment by danieltomasz** [comment]
@mjthoraval Release 1.0.0-3 seemed to fix  it until the Zotero Beta 29 didn't introduced changes to  pdfviewer.

**Comment by mjthoraval** [comment]
@danieltomasz The issue I link to was never fixed and therefore never closed. So it is still the same issue as before.
