### ISSUE TITLE
Beta4 -PDF preview in info pane move from parent item to child item (PDF)

### ISSUE THREAD

**Issue by danieltomasz** [windingwind/zotero-pdf-preview#122]
I am using zotero-pdf-preview plugin beta 4 and Zotero beta 38 (as noted in this issue: https://github.com/windingwind/zotero-pdf-preview/issues/121).

When I click on a child item in my Zotero library, the PDF preview will disappears from the parent item pane and since then will be only visible at the child item level. The view disappears for all other items in my library then as well.

Resizing the main Zotero window temporarily fixes the issue - the PDF preview reappears in the info tab of the parent Zotero item. However, this is only until I click on the child PDF again, at which point the preview disappears from the parent item info pane once more.

By "child item view" I mean this

![image](https://github.com/windingwind/zotero-pdf-preview/assets/7980381/3c1cead3-c07d-40b4-b349-0e006b093dad)
 
I am on MacOS.

**Comment by mjthoraval** [comment]
Probably this one: https://github.com/windingwind/zotero-pdf-preview/issues/104?

**Comment by danieltomasz** [comment]
Yes, this is similar issue, but for me just click on the child item induce this  behaviour and moving to other monitor (which cause Zotero window to resize) temporarily fixes it (or restart). I used plugin version 1.00-3 and didnt experienced this issue before.

**Comment by vancleve** [comment]
I see this too.
