### ISSUE TITLE
安装 PDF previewer 之后右边栏总有部分空间被占用

### ISSUE THREAD

**Issue by liut14** [windingwind/zotero-pdf-preview#123]
zotero 7 beta 38
pdf Previewer 1.0.0-4

如图所示
![image](https://github.com/windingwind/zotero-pdf-preview/assets/52646263/88cc28fb-d0de-4079-9e2d-dcb7a3bce724)

如果关掉 PDF previewer 就可以正常显示
![image](https://github.com/windingwind/zotero-pdf-preview/assets/52646263/0fdd668b-8c2d-41ac-92a8-1b638606c938)

在信息面板中关掉了 info 界面下 显示 预览

操作系统  win10

**Comment by QMike0** [comment]
顶一下，我也遇到了同样的问题
右边栏下方出现大块空白占用空间
![image](https://github.com/windingwind/zotero-pdf-preview/assets/43239563/2372c16f-b92f-414b-aa86-366f8c37d429)

**Comment by mewinners** [comment]
same here!
