### ISSUE TITLE
Installation does not work on MacOS

### ISSUE THREAD

**Issue by laffan** [windingwind/zotero-pdf-preview#124]
I'm using the latest version of Zotero (6.0.26), and MacOS (13.5.1)

I get the following message when trying to install. 

 <img width="470" alt="Screenshot 2023-08-30 at 11 23 26 AM" src="https://github.com/windingwind/zotero-pdf-preview/assets/5421145/4b2120c0-822f-4d91-9a64-c5ea64e20941">

**Comment by mjthoraval** [comment]
The latest stable version of Zotero (6.0.26) should use the latest stable version of the PDF Preview plugin ([Release 0.3.7](https://github.com/windingwind/zotero-pdf-preview/releases/tag/0.3.7)).
The latest beta version of Zotero (7.0.0-beta.38) should use the latest pre-release version of the PDF Preview plugin ([Release 1.0.0-4](https://github.com/windingwind/zotero-pdf-preview/releases/tag/1.0.0-4)).

**Comment by laffan** [comment]
This error appears with Zotero (6.0.26) and PDF Preview plugin ([Release 0.3.7](https://github.com/windingwind/zotero-pdf-preview/releases/tag/0.3.7)).

**Comment by xaviervasco** [comment]
This is happening because you're installing the pre-released version of the plug-in. Scroll down to the green (latest) version. Best
