### ISSUE TITLE
大佬，Mac插件安装上预览页面不会在文献信息下面显示了，请问下是 bug 吗？望回复

### ISSUE THREAD

**Issue by Zhangxigu** [windingwind/zotero-pdf-preview#125]

**Comment by mjthoraval** [comment]
What versions of Zotero and the plugin do you have installed?
What settings are you using?

**Comment by Zhangxigu** [comment]
I'm currently using zotero 7, which I didn't set up, and it worked for a while after I downloaded and installed it, but now it's not working.




发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Marie-Jean Thoraval ***@***.***&gt;
发送时间: 2023年9月4日 15:36
收件人: windingwind/zotero-pdf-preview ***@***.***&gt;
抄送: Zhangxigu ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [windingwind/zotero-pdf-preview] 大佬，Mac插件安装上预览页面不会在文献信息下面显示了，请问下是 bug 吗？望回复 (Issue #125)





 
What versions of Zotero and the plugin do you have installed?
 What settings are you using?
