### ISSUE TITLE
希望能够预览网页快照类型的附件【Feature Request】

### ISSUE THREAD

**Issue by XoYaPeng** [windingwind/zotero-pdf-preview#128]
希望能够预览网页快照类型的附件，很实用的功能！感谢大佬 ，不知这个是否可以实现

**Comment by mjthoraval** [comment]
Is this a duplicate of this one: https://github.com/windingwind/zotero-pdf-preview/issues/85?

**Comment by XoYaPeng** [comment]
@mjthoraval yes
