### ISSUE TITLE
.jpeg Preview?

### ISSUE THREAD

**Issue by xaviervasco** [windingwind/zotero-pdf-preview#129]
I am more and more using Zotero as a repository for reference images as well as .pdfs. However, a lack of an image preview makes this tedious working with titles alone. Could you add support .jpegs into the preview window? Much appreciated!

**Comment by kalshyre** [comment]
I second this! Preview for images would be a big plus, especially jpg and png. I increasingly add images to my Zotero library and cross-reference them with other items. Being able to quickly see a preview on the side (if not thumbnails in the middle pane) would be amazing!

**Comment by eatse21** [comment]
Hi, see #41 (I’m also interested btw!)
