### ISSUE TITLE
无法正常预览 zotero版本：7.0.0-beta.28+3a43a98f1 (64-bit)

### ISSUE THREAD

**Issue by Zhs444** [windingwind/zotero-pdf-preview#131]
请问无法正常预览怎么办？
![image](https://github.com/windingwind/zotero-pdf-preview/assets/146480541/166b6e05-d2e7-4759-a78b-8d6304cfb75a)
zotero版本：7.0.0-beta.28+3a43a98f1 (64-bit)
插件版本：1.0.0-4

**Comment by mjthoraval** [comment]
Can you try the latest [Zotero 7 Beta](https://www.zotero.org/support/beta_builds) (7.0.0-beta.42 at the moment) with the [Pre-release 1.0.0-4](https://github.com/windingwind/zotero-pdf-preview/releases/tag/1.0.0-4) of the plugin?
