### ISSUE TITLE
[Announcement] No update will be made until the Zotero 7 stable version is released

### ISSUE THREAD

**Issue by windingwind** [windingwind/zotero-pdf-preview#133]
Hi there,

Thanks for using this plugin. I have decided that no update will be made until the Zotero 7 stable version is released. The reasons are as follows:

1. This plugin works well on Z6 and is usable on Z7 beta (although not perfect)
2. Most of the issues related to the Z7 version of the plugin lie in the UI. However, Zotero's UI can probably be changed anytime, so any effort and time I spend on solving these issues will be nonsense.
3. I have spent too much time on this plugin and I expect to be very busy in the following weeks.

This does not mean I will give up this project. I will continuously pay attention to the issues (but probably no response will be made if not necessary) and come back with a big update when Z7 stable is out. Thanks for the understanding.

Best,

**Comment by paolovolterra** [comment]
it doesn't work in my Z6...

**Comment by windingwind** [comment]
@paolovolterra https://github.com/windingwind/zotero-pdf-preview/issues/107
Please do a search before asking
