### ISSUE TITLE
安装了插件但是无法使用

### ISSUE THREAD

**Issue by heyeruoqi** [windingwind/zotero-pdf-preview#134]
版本：7.0.0-beta.46+c27bac2ad
电脑系统：Macos 13

**Comment by 11good11** [comment]
我是windows11 安装版本7.0.0-beta.47+f012a348a 也是无法使用

**Comment by mjthoraval** [comment]
Are you using the [Release 1.0.0-4](https://github.com/windingwind/zotero-pdf-preview/releases/tag/1.0.0-4) for Zotero 7 Beta?
At which step do you have the problem? Can you install the plugin?

**Comment by 11good11** [comment]
> Are you using the [Release 1.0.0-4](https://github.com/windingwind/zotero-pdf-preview/releases/tag/1.0.0-4) for Zotero 7 Beta? At which step do you have the problem? Can you install the plugin?

Yes, I have installed the latest version of the plug-in, but the window has not changed
![image](https://github.com/windingwind/zotero-pdf-preview/assets/73817578/d088fe8d-92bd-4421-89bb-77376693b214)
![image](https://github.com/windingwind/zotero-pdf-preview/assets/73817578/4c5a013f-644e-4e6a-82be-b65f7f64ca4a)
![image](https://github.com/windingwind/zotero-pdf-preview/assets/73817578/2c4323f1-f6d2-4857-8bb5-eed376d961da)

**Comment by 11good11** [comment]
> Are you using the [Release 1.0.0-4](https://github.com/windingwind/zotero-pdf-preview/releases/tag/1.0.0-4) for Zotero 7 Beta? At which step do you have the problem? Can you install the plugin?
今天又正常了，我把设置里面的勾选完后就好了
![image](https://github.com/windingwind/zotero-pdf-preview/assets/73817578/23c49a16-aeae-473e-aa3b-92608762b4f9)

![image](https://github.com/windingwind/zotero-pdf-preview/assets/73817578/81bdbf8a-1a12-47c4-9f98-65add1bd4a29)
