### ISSUE TITLE
 the extra "%S" can't be installed

### ISSUE THREAD

**Issue by wanemac** [windingwind/zotero-pdf-preview#135]
Hello, I can't even install the plugin. It says that the extra "%S" can't be installed. It could be incompatible with this version of Zotero.

I am using the version 6.0.30 

Thank you

Wanessa

**Comment by windingwind** [comment]
The latest version is for the current version of Z. The prerelease is for Z beta.

https://github.com/windingwind/zotero-pdf-preview/releases/latest
