### ISSUE TITLE
预览窗口问题

### ISSUE THREAD

**Issue by baileichao** [windingwind/zotero-pdf-preview#136]
开启了PDF preview功能后，信息栏下面总有有部分会被挡住，如下图红色框出的区域，希望可以解决一下。
![image](https://github.com/windingwind/zotero-pdf-preview/assets/57392772/078c1046-e493-4a66-9f0b-7fc1fc6feb6c)

**Comment by Sinoftj** [comment]
是的哦，我这还经常失去功能
