### ISSUE TITLE
(Add-on Installation Failed). The add-on "%S" could not be installed. It may be incompatible with this version of Zotero.

### ISSUE THREAD

**Issue by rzy0901** [windingwind/zotero-pdf-preview#139]
Zotero verison: 6.0.30
<img width="442" alt="image" src="https://github.com/windingwind/zotero-pdf-preview/assets/66763689/e6a3f464-14b1-429a-9daa-6db567501edb">

**Comment by medium-old** [comment]
Having same issue, just installed Zotero onto new laptop and am trying to download plugins again.

**Comment by windingwind** [comment]
thank you for letting me know. i've updated the README.

> For Zotero 6, install the [latest stable version](https://github.com/windingwind/zotero-pdf-preview/releases/latest); For Zotero 7, install the [latest prerelease version](https://github.com/windingwind/zotero-pdf-preview/releases/)
