### ISSUE TITLE
是否考虑添加一个工具栏

### ISSUE THREAD

**Issue by Geo123abc** [windingwind/zotero-pdf-preview#14]
非常棒的插件，有个建议，是否考虑添加一个工具栏，就类似在浏览器中看PDF文件一样，如下图
![](https://s3.bmp.ovh/imgs/2022/08/26/3a662476dada49d3.png)

谢谢

**Comment by windingwind** [comment]
已计划

**Comment by Geo123abc** [comment]
> 

期待，感谢

**Comment by windingwind** [comment]
仅会在工具栏添加部分功能，不希望做得太复杂。像这样可以吗？除了缩放还需要什么功能

![image](https://user-images.githubusercontent.com/33902321/195299427-fd3a3a4f-9281-4c0f-866c-866fc987e28d.png)

**Comment by Geo123abc** [comment]
> 仅会在工具栏添加部分功能，不希望做得太复杂。像这样可以吗？除了缩放还需要什么功能
> 
> ![image](https://user-images.githubusercontent.com/33902321/195299427-fd3a3a4f-9281-4c0f-866c-866fc987e28d.png)

强，感觉足够用了，不过如果可以的话，添加一个显示当前页码的数字，更好一些

**Comment by mjthoraval** [comment]
After zooming, I would find it useful to get a "Fit to Width" button to reset to the default view.
If the zoom is enabled, will it also be accessible from the Ctrl+Scrolling when hovering?

I observe from time to time that the preview zooms in every time it refreshes. The only way to fix that is to close Zotero and reopen. I haven't managed to track down the problem yet. In that situation, a "Fit to Width" button would also be useful.

Would it be possible also to disable the toolbar from the preferences? On a small screen, I would probably still prefer to save space.
Do you plan to have this toolbar in both the Info Tab and the Preview Tab? If the toolbar can be displayed in both, can in be hidden separately for each from the preferences?

Thank you very much!
I have no idea how complicated it is to implement, or how expensive it would be for the CPU and RAM. So I am just suggesting ideas for you to decide what is best.

**Comment by Geo123abc** [comment]
Ctrl+Scrolling is very useful, and I think it is difficult to realize.

**Comment by windingwind** [comment]
@Geo123abc @mjthoraval 

Please try v0.3.0

3 ways to zoom:

toolbar buttons
ctrl & '+'/ctrl & '-'
ctrl & scroll
ctrl & 0 to fit to window.

You can decide which toolabr to hide in prefs.

**Comment by windingwind** [comment]
Currently, the zoom-in/out will have a sudden flash. 

Maybe we should use pdfjs' viewer.js, which would have a fluent zoom experience like in the PDF viewer of Zotero. However, I don't want the preview to be too heavy so it's just a simple realization of zoom.

**Comment by 1067237855** [comment]
[Release 0.3.0](https://github.com/windingwind/zotero-pdf-preview/releases/tag/0.3.0)
![image](https://user-images.githubusercontent.com/104330036/195382642-b0faf427-58c9-41a0-b1cf-07d424c1711f.png)

**Comment by windingwind** [comment]
@1067237855 是的。因为增加了手动缩放功能，所以在后续调整侧栏大小时，将保持原本的缩放比例。
