### ISSUE TITLE
高亮的显示问题

### ISSUE THREAD

**Issue by Geo123abc** [windingwind/zotero-pdf-preview#15]
如题，现在插件对于PDF中高亮笔记似乎是不能正确显示的，还是说我没有设置好？期待更新
PS：[QL-Win/QuickLook: Bring macOS “Quick Look” feature to Windows](  https://github.com/QL-Win/QuickLook  )     预览PDF文件时可以正常显示高亮，不知道能不能借鉴。

**Comment by windingwind** [comment]
支持zotero内的高亮内容显示。

**Comment by Geo123abc** [comment]
> 支持zotero内的高亮内容显示。

是否考虑支持第三方PDF软件做的高亮（储存在PDF文件中，比如 Adobe acrobat、PDF xchange editor）

**Comment by windingwind** [comment]
已支持。

**Comment by Geo123abc** [comment]
> 

厉害了，谢谢，其实我一直对编程感兴趣一些，大体逻辑也知道，但是没有怎么实践过，最近在想要不要系统学习一下编程，搞个小项目啥的，不知道大佬有什么建议吗？

**Comment by Geo123abc** [comment]
> PDF xchange editor

我是用 PDF xchange editor 做的高亮、线条笔记，我更新了，线条可以显示，但是高亮无法显示

**Comment by windingwind** [comment]
> > PDF xchange editor
> 
> 我是用 PDF xchange editor 做的高亮、线条笔记，我更新了，线条可以显示，但是高亮无法显示

不同的软件也许有各自的格式，PDF也有各种不同标准，Zotero并不一定支持所有的PDF批注格式。


> > 
> 
> 厉害了，谢谢，其实我一直对编程感兴趣一些，大体逻辑也知道，但是没有怎么实践过，最近在想要不要系统学习一下编程，搞个小项目啥的，不知道大佬有什么建议吗？

如果对插件有兴趣，可以参见我和其他几个插件作者撰写的开发文档：https://zotero.yuque.com/books/share/8d230829-6004-4934-b4c6-685a7001bfa0/sdihk2

同时我维护了一个面向入门插件作者的插件模板，在这里：https://github.com/windingwind/zotero-addon-template

可供参考。

**Comment by Geo123abc** [comment]
> > > PDF xchange editor
> > 
> > 
> > 我是用 PDF xchange editor 做的高亮、线条笔记，我更新了，线条可以显示，但是高亮无法显示
> 
> 不同的软件也许有各自的格式，PDF也有各种不同标准，Zotero并不一定支持所有的PDF批注格式。
> 
> > > 
> > 
> > 
> > 厉害了，谢谢，其实我一直对编程感兴趣一些，大体逻辑也知道，但是没有怎么实践过，最近在想要不要系统学习一下编程，搞个小项目啥的，不知道大佬有什么建议吗？
> 
> 如果对插件有兴趣，可以参见我和其他几个插件作者撰写的开发文档：https://zotero.yuque.com/books/share/8d230829-6004-4934-b4c6-685a7001bfa0/sdihk2
> 
> 同时我维护了一个面向入门插件作者的插件模板，在这里：https://github.com/windingwind/zotero-addon-template
> 
> 可供参考。

谢谢，你做高亮是使用zotero自带的阅读器吧？

**Comment by windingwind** [comment]
和自带阅读器一样，依赖于zotero中的pdf.js，严格意义上来说并不是自带的阅读器，而是它的一个简化版本（用于快速预览）

**Comment by Geo123abc** [comment]
> 和自带阅读器一样，依赖于zotero中的pdf.js，严格意义上来说并不是自带的阅读器，而是它的一个简化版本（用于快速预览）

好的，了解了，但是我觉得一般做的高亮之类的，只要是存储在PDF中，应该都能显示。我用quicklook预览的时候，是可以显示所有高亮的，我先看看后续版本吧，这个暂时不是刚需

**Comment by windingwind** [comment]
quicklook和这个原理不同。这个不是核心功能，我只能花有限的时间做主要的功能，欢迎补充
