### ISSUE TITLE
Conflict with earlier plugin ZoteroPreview

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-pdf-preview#16]
This plugin breaks the earlier plugin [ZoteroPreview](https://github.com/dcartertod/zotero-plugins) by dcartertod.
When the two plugins are enabled, the Citation Preview does not update anymore.
You need to click on the PDF Preview tab and then go back to the Citation Preview tab to get the citation preview updated.
Tested on Windows 10, Zotero 6.0.14-beta.1+79246196a

**Comment by windingwind** [comment]
This is a Zotero Preview plugin side bug. It uses the absolute index `4` in tabs to locate the tab panel, which is not a standard way.

https://github.com/dcartertod/zotero-plugins/blob/be033feb3fac8163d6e4e3eda604f78613a758d5/ZoteroPreview/chrome/content/zoteropreview.js#L96

I suggest you report this bug to that plugin along with this issue link.

**Comment by mjthoraval** [comment]
Thank you for looking into this and posting the details in the other plugin's GitHub.
