### ISSUE TITLE
功能增强：让预览窗口一直在右边栏切分成上下两部分的下部分中，即使切换上边的面板

### ISSUE THREAD

**Issue by ghweili** [windingwind/zotero-pdf-preview#17]
目前仅当上侧为info 面板时下侧可以显示预览，而当切换到其他面板，比如标签面板或note面板，此时下方的预览面板会消失。如果能上面切换不同面板都不影响下边的预览窗口会比较方便 

![image](https://user-images.githubusercontent.com/33361275/187081405-1167278a-8b66-4696-abb9-b186266394e2.png)

**Comment by windingwind** [comment]
如果切换到非pdf的条目，只会保留上一个预览的内容，与当前选中条目无关。是否有意义？

**Comment by ghweili** [comment]
不是切换到非pdf条目，而是说右侧面板从info切换到其他页面，比如tags面板或者notes面板。我经常会在notes面板对文章做些简单的记录，下次选中该条目时，如果右侧能同时显示pdf和note或者tags等，则会比较方便

**Comment by windingwind** [comment]
这相对复杂，将尝试
