### ISSUE TITLE
希望可以适配zotero-night插件

### ISSUE THREAD

**Issue by ishield** [windingwind/zotero-pdf-preview#2]
目前在zotero-night的黑色模式下，还没有适配，麻烦您有时间帮忙适配一下。
该插件非常好，感谢您的开发！

**Comment by windingwind** [comment]
![image](https://user-images.githubusercontent.com/33902321/179334650-b3885734-f5f2-49e0-900c-4ce848dc85c0.png)
已支持黑暗模式预览。在编辑-首选项中设置打开即可
