### ISSUE TITLE
Fit to Window Option

### ISSUE THREAD

**Issue by altugkoc** [windingwind/zotero-pdf-preview#20]
Hello,

First of all let me present my thanks and congratulations for this great plugin. You've definitely covered a necessary lack of Zotero. A very useful feature for quick literature browsing.

The reason I opened the thread is a suggestion rather than an issue. Some e-books may not fit in the preview window because their resolution is too large. There is no zoom in/out feature, but I think it would be very useful if fitting every preview to the window size (both from the sides and from the top and bottom).

Regards,

**Comment by windingwind** [comment]
Thanks for letting me know! I've planned to add a zoom in/out function.

**Comment by windingwind** [comment]
like this?
![image](https://user-images.githubusercontent.com/33902321/195299900-87c21de6-f87b-4793-a876-46b5757e69ab.png)

**Comment by altugkoc** [comment]
Amazing!

**Comment by windingwind** [comment]
Please try v0.3.0

3 ways to zoom:
1. toolbar buttons
2. ctrl & '+'/ctrl & '-'
3. ctrl & scroll

ctrl & 0 to fit to window.
