### ISSUE TITLE
增加外部PDF阅览器的选项

### ISSUE THREAD

**Issue by Geo123abc** [windingwind/zotero-pdf-preview#22]
zotero 本身有这个选项：zotero选项 - 常规 - 打开PDF使用，当在条目区双击条目的时候会用此处设置的阅读器打开PDF
现在 ，zotero-pdf-preview 双击预览页面以打开/转跳PDF 应该也是和上面的设置保持一致的

能否增加一个选项，允许用户自定义PDF阅读器，比如 C:\Program Files (x86)\Adobe\adobe.exe  或者zotero自带的PDF阅读器  ，这样的话，就能和zotero本身的进行区分了

**Comment by windingwind** [comment]
谢谢建议，我将在未来版本的工具栏上增加一个按钮用于外部阅读器打开。

**Comment by Geo123abc** [comment]
其实自定义在预览界面双击打开方式是最好，因为
1. 在条目上双击是zotero软件自带的设置
2. 在预览界面双击、打开和1如果能互为补充的话，是很方便的，并且预览那个地方的区域比较大
3. 如果是在工具栏添加按钮，这个按钮应该是比较小吧，操作起来可能不太方便
4. 按钮这种方式在青柠的一个插件上已经实现，上述反馈也是基于操作体验不方便

**Comment by Geo123abc** [comment]
您好，我又来冒泡了，现在preview的功能很强大了，外部阅读器的高亮注释也都能显示
我来再问一下，能不能在放大、缩小工具栏旁边加一个或者两个按钮，功能是使用用户设置的外部阅读器打开PDF文件
谢谢
