### ISSUE TITLE
能否實現預加載或快取其他項目

### ISSUE THREAD

**Issue by r888800009** [windingwind/zotero-pdf-preview#23]
必須選取才會進行加載預覽，有可能把這段時間省去掉？

這個想法是，使用者可能點選顯示出的項目列表的任一項目，或者用上下鍵預覽前後的項目。

有幾個想法
1. 滑鼠停在某個項目的時候會先行加載
2. 加載當前項目的上下 n 個項目
3. 加載列表顯示的所有項目
4. 預加載只載入 pdf 的 1, 2 頁
5. 加載列表中，前幾個最常預覽的項目

另外使用者可能會重複預覽幾個項目
1. 加上 cache 去保存先前預覽的 n 個項目

不知道 zotero 的 api 是否可以實現這類的功能?

謝謝

**Comment by windingwind** [comment]
感谢建议。我有空看一下现在的预览速度瓶颈是在哪里，以确定预加载是否能够提升在项目之间切换的速度。

对于配置较低的电脑，预加载可能反而降低性能，因为增加了内存占用以及后台活动（预加载）。这可能也需要考虑。

对于建议的回复：

> 滑鼠停在某個項目的時候會先行加載

我认为这会带来较大的卡顿，因为Zotero无法事实上实现多进程或多线程。

> *加載當前項目的上下 n 個項目

这也许可行

> 加載列表顯示的所有項目

会带来很大的内存占用，不应该这样做

> *預加載只載入 pdf 的 1, 2 頁

可考虑

> 加載列表中，前幾個最常預覽的項目

这要维护一个常访问项目的列表，似乎过于复杂了。

> *加上 cache 去保存先前預覽的 n 個項目

可考虑

星号标出的建议将可能会采纳。谢谢！
