### ISSUE TITLE
新版本（0.3.0）无法预览

### ISSUE THREAD

**Issue by A-stupid-fish** [windingwind/zotero-pdf-preview#24]
更新后，无论中英文都无法预览

**Comment by windingwind** [comment]
请截图并详细描述。

**Comment by zyx335588** [comment]
@windingwind  
出现相同的问题，表现如 https://github.com/windingwind/zotero-pdf-preview/issues/25#issue-1407169494 所述

@A-stupid-fish 
我根据 @mjthoraval 在 https://github.com/windingwind/zotero-pdf-preview/issues/25#issuecomment-1277170670 到方法解决了预览问题。将首选项中的下列位置填入需要的数字（似乎默认页码没有起作用）
![image](https://user-images.githubusercontent.com/22871049/195590559-682d3253-c24a-4afc-b1c2-a3032eec8376.png)

**Comment by windingwind** [comment]
感谢提示，我排查到是由于更新时错误删除了默认预览页码。已修复在0.3.1
