### ISSUE TITLE
Broken preview in Release 0.3.0

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-pdf-preview#25]
The PDF preview does not display anymore for me in Release 0.3.0:
![image](https://user-images.githubusercontent.com/36054098/195509931-dc3df13b-91cd-4f62-98c7-0f4e82c9a963.png)
Using Windows 10, Zotero 6.0.16-beta.3+29dd0cf5d
I have tried to disable all other plugins, but I still get the same.

**Comment by mjthoraval** [comment]
Here is a [screen recording](https://drive.google.com/open?id=11P-4HesUivsDRmj1ewF29Zl6XGgY3_CN&authuser=mjthoraval%40gmail.com&usp=drive_fs) showing several issues.

Even though I have selected in the preferences not to show the toolbar, it still appears for a short time around 0'53".

I managed to get it to work again by changing the value of "Preview First ___ Pages(See GitHub for advance usage)" 
[NB: Add a space between "Pages" and "(".]

Another remark: Changing the "Preview Tab Name" needs to restart Zotero to be effective. Is it the expected behaviour?

At around 1'04" in the video, the panes seem to be jumping around for some reasons. I have seen that behaviour happening for a long time, but it recovers automatically every time, so I did not take the time to report. Do you know what is happening at that time?

**Comment by Strain-solutions** [comment]
Just to add I have this same issue. Adding a number to the 'Preview first ___ does appear to fix the issue, however for me the pdf that is shown doesn't refresh when I click on a different record.  i.e. I always shows the same PDF regardless of the selected record.

**Comment by mjthoraval** [comment]
The preview is changing for me when clicking on different items, but it does not seem to be very reliable:
![image](https://user-images.githubusercontent.com/36054098/195577413-086ffd75-4c31-4bc5-a07a-4bc5a14f1f1d.png)
I haven't managed to track down how to reproduce.

**Comment by windingwind** [comment]
Sorry for the bug. I've fixed in the v0.3.1

**Comment by windingwind** [comment]
> however for me the pdf that is shown doesn't refresh when I click on a different record

@Strain-solutions If that still happens, we could discuss in a new thread.

> The preview is changing for me when clicking on different items, but it does not seem to be very reliable:

@mjthoraval Does this happen in earlier versions 0.2.x? The logic of selection change listener is not updated.

**Comment by mjthoraval** [comment]
I have managed to get these steps to reproduce the inconsistent preview:
https://github.com/windingwind/zotero-pdf-preview/issues/26

But overall, the loading of the plugin (at first use after opening Zotero) is still very slow, with the panes jumping around as you can see in the screen recording above. Any idea on this?

**Comment by windingwind** [comment]
@mjthoraval 
I've move the loading stage to the moment Zotero is started. Does that helps?
