### ISSUE TITLE
Zoom: Shortcut `Ctrl`+`+` not working

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-pdf-preview#28]
I am using a keyboard with a separate part on the right for the number, which includes + and -.
If I try the shortcut `Ctrl`+`-` (next to the numbers on the right of the keyboard), it zooms out.
But if I do `Ctrl`+`+` (next to the numbers on the right of the keyboard), nothing happens.
Pressing the `+` in the toolbar, or `Ctrl`+Scroll works well.

I am using a French keyboard. I am not sure if that is important. But I guess the keyboard layout should not affect the +/- on the right part of the keyboard.

For the +/- on top of the letters, they also behave in a strange way.
On the French keyboard, the minus is just below the 6 (the 6 is activated with `Shift` on the French keyboard). It works as expected with using the shortcut `Ctrl`+`-`.
But the + should be activated when used together with `Shift`, as the `+` is above the `=` key. But the shortcut only works when doing `Ctrl`+`=` (below the `+` above the letters) and the `Ctrl`+`+` that should be activated with the `Shift` does not work.
This part is fine actually, as long as I remember about it. I mainly mention it in case it is related to the problem reported above.

**Comment by windingwind** [comment]
fixed in v0.3.2

**Comment by mjthoraval** [comment]
Thank you very much.
I confirm that it is working now.
