### ISSUE TITLE
内置笔记无法在预览中显示

### ISSUE THREAD

**Issue by fengyelai** [windingwind/zotero-pdf-preview#3]
您好，zotero内置笔记目前无法显示（未提取保存到pdf），是否有后续开发计划呢？谢谢

**Comment by windingwind** [comment]
更新后在首选项打开注释预览

**Comment by fengyelai** [comment]
感谢如此优秀的插件，按照您的指点我尝试了更新并看到了预览中的笔记，但是也经常出现部分pdf的内置笔记无法显示的情况。谢谢

**Comment by windingwind** [comment]
> 感谢如此优秀的插件，按照您的指点我尝试了更新并看到了预览中的笔记，但是也经常出现部分pdf的内置笔记无法显示的情况。谢谢

请截图注释未显示条目的内置阅读器界面+预览界面

**Comment by fengyelai** [comment]
![image](https://user-images.githubusercontent.com/33919191/179350792-211ed8f7-5a63-449c-bfa7-3705f6c4c4f9.png)
![image](https://user-images.githubusercontent.com/33919191/179350819-e476f823-c9a8-4d8d-82d0-5c2e21f05873.png)
以上是图片

**Comment by windingwind** [comment]
这些注释是在zotero中添加的还是在外部编辑器添加的呢

**Comment by fengyelai** [comment]
是用的zotero中的内置笔记工具，有的没问题，有一些pdf会不现实，我尝试一些方法，好像无济于事。

**Comment by windingwind** [comment]
> 是用的zotero中的内置笔记工具，有的没问题，有一些pdf会不现实，我尝试一些方法，好像无济于事。

请将出问题的pdf文件发在这里

**Comment by fengyelai** [comment]
[Albarracín 等。 - 2017 - Responses of vegetative growth and fruit yield to .pdf](https://github.com/windingwind/zotero-pdf-preview/files/9125628/Albarracin.-.2017.-.Responses.of.vegetative.growth.and.fruit.yield.to.pdf)
因为是内置阅读器的bij笔记，单独的pdf无笔记，您可以添加试试

**Comment by windingwind** [comment]
已修复
