### ISSUE TITLE
Incompatiblity with BBT v6.7.25 in 0.3.3

### ISSUE THREAD

**Issue by daaaaaaaaaniel** [windingwind/zotero-pdf-preview#30]
The latest update 0.3.3 seems to have introduced new incompatibility with [Better BibTeX v6.7.25](https://github.com/retorquere/zotero-better-bibtex ). In the latest version of these plugins, the PDF preview window fails to display the PDF in the Info pane. It leaves an empty white box where it should appear. This occurs when a parent item is selected in the main window. It is not an issue when selecting a child PDF attachment in the main window. 

This issue was not present in the previous versions of this plugin or BBT.

**Comment by volatile-static** [comment]
maybe problems here:
https://github.com/windingwind/zotero-pdf-preview/commit/95f4d0f2c8801ff7c3dcab2246a1fc708f6881ea#diff-4a04ca6a30d68873b6ce33d20edabe4d8968252ff912b8d703897ddc8d225679L126-L138
