### ISSUE TITLE
Jumping between tabs when loading BBT

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-pdf-preview#32]
I have finally managed to identify this behaviour, that I had already reported in a [previous post](https://github.com/windingwind/zotero-pdf-preview/issues/25#issuecomment-1277170670).
The jumping between different tabs seems to be triggered by the loading of the BBT Citation Keys.
See at around 1'06" of this [screen recording](https://drive.google.com/open?id=11nJeJUTg9O6lF3Lst8NASDaoz9PSPvlU&authuser=mjthoraval%40gmail.com&usp=drive_fs).

The Info Tab in the Item Pane is reloaded by BBT at that time. So it is probably something in that plugin.
But I only observe this behaviour with the PDF Preview plugin.
It would be useful to identify the origin of the problem and see which plugin needs to be updated to fix this. Let me know if I should open an issue in the BBT plugin's GitHub page.

During the loading of Zotero, the preview toolbar appears, even though it is not selected in the Preferences.
After the jumps between tabs, some remaining of the toolbar still appears on the left side of the preview. Clicking on another item fixes the problem. So it is not a big issue. But it would still be nice to fix it.

Using Zotero 6.0.16-beta.4+410ebc288, Better BibTex for Zotero 6.7.26, Zotero PDF Preview 0.3.4 on Windows 10.

**Comment by mjthoraval** [comment]
Thank you for the fix.
The view is still jumping between tabs and moving panes around when loading the BBT Citation Keys. But now the PDF Preview is able to recover at the end.
Is this due to the PDF Preview plugin, or is it due to BBT?

**Comment by windingwind** [comment]
Jumping between different two tabs is the preview's behavior to avoid strange looking of the splitter.

The BBT changes the layout of info pane after the window is loaded, so we must wait until BBT finished its loading and refresh the info pane, as it is modified by BBT. During this refreshing, the splitter is strange and the only workaround is to switch to another tab and then switch back. That's what's happening during the loading stage if BBT is on.

The strange looking of the splitter. It disappears and the mouse has a horizontal;y-dragging icon, which is expected to be a vertically-dragging icon.
![image](https://user-images.githubusercontent.com/33902321/196147950-56d7fe1d-04f0-440b-8f43-5605ac27afa2.png)

**Comment by mjthoraval** [comment]
Thank you for the explanation.
