### ISSUE TITLE
PDF display/preview gets fixed on one PDF

### ISSUE THREAD

**Issue by DavidWHouse** [windingwind/zotero-pdf-preview#33]
Using Zotero 6.0.15, PDF Preview 0.3.4 of 10/16/22, Windows machine. Sometimes PDF Preview (bottom pane in Info tab, and Preview tab both) will 'fix' on one PDF seen previously in the session and will display that PDF for all items where there is a PDF. As yet, I have not figured out how to invoke the behavior, but it seems to have something to do with adding items that have PDFs. I changed the number of pages previewed (thinking that would 'refresh the cache' or whatever) from 10 pages to 20 pages and if anything, that made it worse.

Exiting Zotero and getting back in seems to resolve the problem as one would expect, but I am not sure that this works in all cases. (Sorry; have not kept notes on the issue as it occurs.)

**Comment by windingwind** [comment]
Thanks for the report. If that happens again, please go to Help-Output log-View output and paste/upload the logs here.

**Comment by DavidWHouse** [comment]
It seems to have stopped. Sorry for not being able to help further.
