### ISSUE TITLE
为何只显示内置阅读器的高亮标注？

### ISSUE THREAD

**Issue by szjhpz** [windingwind/zotero-pdf-preview#35]
我发现pdf用mac自带的预览或者第三方pdf阅读器高亮标注后，在插件中是不显示这些高亮痕迹的，但是用zotero自带的阅读器标注后，是可以显示的，虽然要加载一下（就像卡顿）。

请问这样正常吗？我用的是mac版zotero，最新版本。

如果第三方标注后的高亮本就无法显示，可否考虑支持一下？

**Comment by volatile-static** [comment]
我这边可以显示外来的批注呀

**Comment by xuzhenwu** [comment]
> 我发现pdf用mac自带的预览或者第三方pdf阅读器高亮标注后，在插件中是不显示这些高亮痕迹的，但是用zotero自带的阅读器标注后，是可以显示的，虽然要加载一下（就像卡顿）。
> 
> 请问这样正常吗？我用的是mac版zotero，最新版本。
> 
> 如果第三方标注后的高亮本就无法显示，可否考虑支持一下？

我是从EndNote转过来的，EndNote的预览可以很好地显示各类阅读器增加的标准。但转zotero后，我这边遇到了同样的问题，用foxit pdf阅读器标注的文档，预览时不显示高亮；而在用zotero自带的阅读器打开一次后，才能预览。这是不是一个技术上的问题？第三方阅读器的标注，并不自动加载？这对于从其他文献管理软件，或习惯使用第三方阅读器标准的人来说，不太方便。

另外，官方阅读器似乎也不支持下划线，这似乎在论坛里讨论过了，后边似乎会更新。
https://forums.zotero.org/discussion/comment/402384/#Comment_402384

**Comment by xuzhenwu** [comment]
如图，
![image](https://github.com/windingwind/zotero-pdf-preview/assets/40906600/956c6d3f-7c8d-4b0e-b9b0-99d3848e5128)
![image](https://github.com/windingwind/zotero-pdf-preview/assets/40906600/8788245a-631e-4892-afb4-451da1eea312)
![image](https://github.com/windingwind/zotero-pdf-preview/assets/40906600/2c3f033b-12a7-4966-8b46-9072902353da)
