### ISSUE TITLE
Preview Images as well, not only PDF's

### ISSUE THREAD

**Issue by rucativava** [windingwind/zotero-pdf-preview#41]
Hello,

Your plugin is spot on for quickly checking a PDF. Its interface would be perfectly suited to be able to quickly view a JPG or PNG as well. As far as I see, this would be important to empower Zotero as a full research/file management system, not only PDF's. 
Has this idea been considered yet?

**Comment by volatile-static** [comment]
duplicate #10

**Comment by kalshyre** [comment]
I also support this. I have a lot of images in my Zotero (screengrabs from various origins, field photos etc. for reference purposes) and it's great to keep everything in the same place and be able to quickly preview them without opening a dedicated viewer.
