### ISSUE TITLE
Adding an option to preview notes?

### ISSUE THREAD

**Issue by champagnealexandre** [windingwind/zotero-pdf-preview#47]
Hi and thank you for your plugin, I have just discovered it and it has really improved my experience with Zotero.

I’m wondering if there would be a possibility to have an option to preview notes as well. I summarize the papers I read in a note attached to the item and it would be really useful to see the metadata, the PDF _and_ my small summary at the same time. My summaries are usually very short (a few lines) so it would fit nicely in the side pane (maybe above the PDF preview?)

Thanks again.

**Comment by windingwind** [comment]
I'm not sure what the UI should look like if we support a note preview.

What should we do if there are multiple child notes under an item?

**Comment by champagnealexandre** [comment]
> I'm not sure what the UI should look like if we support a note preview.

Example image below—of course without the additional menu bar, toolbar and status bar that take useless space here.

> What should we do if there are multiple child notes under an item?

Show the first note alphabetically (or another user-defined criteria), or show multiple notes inside tabs?

<img width="509" alt="image" src="https://user-images.githubusercontent.com/30211986/207761635-5e87a7db-7b12-4c56-a23b-e5327ae8bc1a.png">
