### ISSUE TITLE
快速切换文献时CPU占用高

### ISSUE THREAD

**Issue by xinze98** [windingwind/zotero-pdf-preview#5]
我的电脑（CPU i5-7500，内存22GB）开启文献预览插件的状态下，在快速切换文献的时候CPU占用率会急剧升高，甚至达到100%（右侧没有显示预览窗口，而是仅仅显示文献信息页的情况下），然后电脑就会开始卡顿，感觉是他后台预加载pdf导致的，大佬能否优化一下预加载机制？这样在老旧CPU上的使用体验会好一点。

**Comment by windingwind** [comment]
已修复

**Comment by xinze98** [comment]
多谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "windingwind/zotero-pdf-preview"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月28日(星期四) 晚上7:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [windingwind/zotero-pdf-preview] 快速切换文献时CPU占用高 (Issue #5)





 
已修复
