### ISSUE TITLE
If references have DOI, the pdf can't be previewed.

### ISSUE THREAD

**Issue by earthmoon** [windingwind/zotero-pdf-preview#55]
Hello,
All of my references can't be previewed, as they all have DOI. May this add-on will be modified to automatically select the pdf to previewed, not care about any other format files?
![Screenshot 2023-01-03 144453](https://user-images.githubusercontent.com/45897471/210380019-5855cc0b-ceb8-4472-aebb-5c18954ab10e.png)

**Comment by windingwind** [comment]
I’m not sure why, but seem like the parent item is not a correct type.

Obviously it is not related to DOI. I will test it out.

**Comment by earthmoon** [comment]
> 
Thanks for your kindle reply. What is the parent item? If you need any files to test, please let me send it to you. Thanks.

**Comment by windingwind** [comment]
Not sure what you mean by *all references cannot be previewed*. The parent item is the item which your pdf attachment belongs to.

Attach the pdf file in this thread or mail me at wyzlshx@foxmail.com

Thanks for the feedback.

**Comment by earthmoon** [comment]
> Not sure what you mean by _all references cannot be previewed_. The parent item is the item which your pdf attachment belongs to.
> 
> Attach the pdf file in this thread or mail me at [wyzlshx@foxmail.com](mailto:wyzlshx@foxmail.com)
> 
> Thanks for the feedback.

Hello,
I have sent you email with attachments. Maybe all of my references were imported from Endnote or CItavi, there are some format that is incompatible with zotero.
Thanks.
