### ISSUE TITLE
在 信息 界面显示的 PDF预览窗口会自动闪烁

### ISSUE THREAD

**Issue by tangjyan** [windingwind/zotero-pdf-preview#6]
zotero十几分钟到几十分钟不操作，PDF预览窗口就会无故闪烁

**Comment by windingwind** [comment]
由于没有具体的描述，我不清楚是由其他插件或是zotero的一些后台同步/刷新rss订阅等操作导致，很难针对性排查问题。
理论上，窗口闪烁即是由于选中条目发生改变而进行刷新。如果刷新前后的pdf源没有改变，则不会实质上占用cpu或者额外内存，不影响性能。

**Comment by windingwind** [comment]
新版本可能修复了该现象

**Comment by tangjyan** [comment]
> 新版本可能修复了该现象

从信息切换其他标签再切换回信息标签，pdf预览就成空白了，100%复现

**Comment by windingwind** [comment]
已修复
