### ISSUE TITLE
preview somehow start not showing the whole last page with ":" setting

### ISSUE THREAD

**Issue by yzliu01** [windingwind/zotero-pdf-preview#64]
Could you help with this issue that the last page is not shown or not shown completely, only half shown? Thanks.

one example
![image](https://user-images.githubusercontent.com/93487645/216790030-a9399af6-6024-403e-b0eb-723b3bccc54b.png)

another one

![image](https://user-images.githubusercontent.com/93487645/216789801-2c58599a-c663-45aa-a1ed-464e846e6524.png)

**Comment by windingwind** [comment]
The tab panel content overflows sometimes. The XUL elements do have strange display behaviors, which we cannot help.

Restarting Zotero will restore the view.
