### ISSUE TITLE
Mac os下无法调整首选项

### ISSUE THREAD

**Issue by Sunbuyu** [windingwind/zotero-pdf-preview#7]
机型：MacBook Pro (13-inch, M1, 2020)
系统：Monterey 12.5
在首选项栏没有调整预览首选项的窗口，但是另外的Zotero Tag有这个调整的插件，不知道是不是插件的bug。
![image](https://user-images.githubusercontent.com/52070155/182340497-8a3511cf-0023-430c-ba1b-0a901d471cad.png)

**Comment by windingwind** [comment]
请更新插件版本
