### ISSUE TITLE
Preview with multiple PDF files

### ISSUE THREAD

**Issue by roentgenium** [windingwind/zotero-pdf-preview#71]
This plugin works fine. I would like to thank you for sharing this.

In my field, a scientific paper sometimes comes with a few supporting information files (e.g. another pdf file).
Zotero Connector magically imports not only the main text but also a supporting information pdf file. It's fine.

Then, when I click an time title (not pdf files), the preview plugin always displays the second (?) attached file of the supporting information file.
It would be nice to see the first pdf file (i.e. the main text) although I do not know the attached files are numbered internally or not.

Is there any setting parameters or workaround?

**Comment by windingwind** [comment]
The plugin uses Zotero API to find the best match attachment. Maybe you could ask in the forums to get the details of how it works.

There is no such definition as `the first PDF`, as they can be sorted according to different columns, e.g. title, time, and author. I'm sorry this might not be possible.

**Comment by roentgenium** [comment]
Thank you so much for your response.
It's a pity I cannot make an order of attached files, but still very nice. 
Thank you again.
