### ISSUE TITLE
Bug: Cannot find page for "Preview" in the preference window

### ISSUE THREAD

**Issue by crliu95** [windingwind/zotero-pdf-preview#75]
The installation is smooth and preview function works well. But I just cannot find the specific page for this add-on in the "edit-preference" window. Here attached the screen shot of my preference window for now.

![image](https://user-images.githubusercontent.com/20499205/221090840-c6585b69-f723-4c45-86ab-c75a2a6cb19b.png)

p.s. I also find that the short-cuts and zoom in/out function are not working.

Other related info: Zotero in 6.0.22 version, installed on Windows 11 x64

**Comment by windingwind** [comment]
Please check the plugin version.

**Comment by crliu95** [comment]
> Please check the plugin version.

Thanks for your instant reply. The plugin version is 0.0.2, which was new installed just now.

**Comment by windingwind** [comment]
Which is definitely not the latest version. Please update.

**Comment by crliu95** [comment]
> Which is definitely not the latest version. Please update.

Oh! Thanks for your kind reminder. I just found the version is out-of-date, which could be possibly caused by the link through which I was directed to this plug-in. 

All things going well after an upate. Many thx!
