### ISSUE TITLE
PDF的内容有很多显示不出来的情况

### ISSUE THREAD

**Issue by csf2022scut** [windingwind/zotero-pdf-preview#78]
这个PDF用zotero打开会出现很多内容消失的情况
**zotero预览效果**
![image](https://user-images.githubusercontent.com/117445516/222903316-3bf5f005-d8c7-45b0-99b4-b22341e877ce.png)

**实际预览效果**
![image](https://user-images.githubusercontent.com/117445516/222903355-c7a9822f-9733-4bb7-ad0c-052740bf837b.png)

**原PDF文件：**
[shou2021.pdf](https://github.com/windingwind/zotero-pdf-preview/files/10888392/shou2021.pdf)

求解答，谢谢大佬！

**Comment by windingwind** [comment]
请向zotero社区反馈，谢谢！

**Comment by csf2022scut** [comment]
> 请向zotero社区反馈，谢谢！

请问怎么向zotero社区反馈呀？是在forums里边提discussion吗？
