### ISSUE TITLE
启用 Auto Focus 后手动切换 Info 页异常

### ISSUE THREAD

**Issue by faketrader** [windingwind/zotero-pdf-preview#8]
当焦点首次在 Preview 时，首次点击 Info 页后自动切换回 Preview，后续点击 Info 可正常切换，但 Info 页内的预览显示空白。再次手动点击 Preview 页，问题重复。

PDF Preview v0.2.3, Zotero v6.0.11 on macOS

截屏：

![2022-08-04 11-16-49 2022-08-04 11_22_15](https://user-images.githubusercontent.com/9635792/182824658-15c39eba-35e5-4f50-ab82-d657f2293af2.gif)

设置：

<img width="569" alt="WX20220804-112343@2x" src="https://user-images.githubusercontent.com/9635792/182825006-58089695-55f6-4bc2-b95e-0e5796103244.png">

**Comment by faketrader** [comment]
其中信息页预览空白的问题已有人反馈 _Originally posted by @tangjyan in https://github.com/windingwind/zotero-pdf-preview/issues/6#issuecomment-1204935104_

**Comment by windingwind** [comment]
由于已经支持在信息栏预览，且可以手动调整大小，自动选中预览标签功能可被替代。
将在下一版本移除，因此不再存在该问题。
