### ISSUE TITLE
希望能够预览网页快照类型的附件【Feature Request】

### ISSUE THREAD

**Issue by blackwint3r** [windingwind/zotero-pdf-preview#85]
zotero不仅可以管理pdf论文，还可以管理各种各样的文档和资料，比如乐谱、网页、扫描稿、课件等等，加上丰富的元数据管理功能，使它完全可以代替资源管理器，作为类似对象存储的资源管理中心使用，唯一的缺点缺乏可视化的预览功能，而这个插件极大地补足了这个缺点。

但是除了pdf，zotero还能很方便地保存和管理网页快照，而且网页更需要预览功能（因为网页相比pdf文档含有更多的视觉元素，预览的时候获得的信息量更大）。如果这个插件能够预览保存的网页快照，那就完美啦。

**Comment by XoYaPeng** [comment]
希望大佬可以早日加入这个功能！十分实用！感谢！ @windingwind
