### ISSUE TITLE
不兼容问题

### ISSUE THREAD

**Issue by Sherlly110302** [windingwind/zotero-pdf-preview#86]
<img width="698" alt="75e31865a5b12408ecb5f5a1addf0c5" src="https://user-images.githubusercontent.com/132717223/236580742-87b36b93-b5b8-4c27-a57b-f6d45f73d36e.png">
作者您好 我觉得这个插件十分有用 但我安装时 总说不兼容 想问怎么办鸭

**Comment by windingwind** [comment]
请按说明下载安装
