### ISSUE TITLE
Zotero 7 compatibility roadmap

### ISSUE THREAD

**Issue by danieltomasz** [windingwind/zotero-pdf-preview#87]
Are there plans to ensure this plugin compatibility with upcoming Zotero 7?

**Comment by windingwind** [comment]
Aha, this plugin is probably the first one that can run on Z7, several months ago.
Once Z7 comes to beta versions, I will make it available in days.

**Comment by priceperrott** [comment]
Hi. Just wondering what your timeline is on a release of this that will work with Zotero 7 beta versions now out?

**Comment by simonmb** [comment]
The beta version is out...

**Comment by windingwind** [comment]
Yes… But there are more basic things that need to be changed in the latest beta. So maybe another week or two

**Comment by danieltomasz** [comment]
Just linking discussion from BetterBibtex plugin https://github.com/retorquere/zotero-better-bibtex/issues/2522 (might be useful)

**Comment by windingwind** [comment]
done.
See https://github.com/windingwind/zotero-pdf-preview/releases
The latest beta only supports z7.

**Comment by priceperrott** [comment]
Thanks for all your work in releasing this update for Zotero 7.  Much appreciated!
