### ISSUE TITLE
关于内存占用是否可以优化

### ISSUE THREAD

**Issue by iqeix** [windingwind/zotero-pdf-preview#88]
尊敬的开发者您好！首先对您开发PDF预览这一插件表示感谢。
在使用中，我发现当我仅仅通过预览的方式去遍历的浏览我的文献库时，存在内存占用逐渐增加的情况。是否可以添加单个文献预览后执行内存释放操作呢？

**Comment by windingwind** [comment]
每预览10篇会自动清一次内存。
