### ISSUE TITLE
Auto Focus Preview Tab 在设置里面找不到

### ISSUE THREAD

**Issue by youthcould** [windingwind/zotero-pdf-preview#89]
Version 0.3.7
Windows 11
Zotero 6

大佬你好，非常喜欢这个插件，但是每次打开zotero，不会自动focus到preview tab。我看你的readme里面似乎有这个选项，但是我这里找不到这个选项（如下图）。烦请大佬看下。谢谢

![屏幕截图 2023-06-13 051152](https://github.com/windingwind/zotero-pdf-preview/assets/2182992/6045100f-0ee3-4704-9bef-29fff9d8b60c)

**Comment by windingwind** [comment]
该功能已移除。可以在信息tab中直接查看，不需要自动聚焦
