### ISSUE TITLE
挑个刺：中文字体明显慢于英文字体的论文

### ISSUE THREAD

**Issue by tangjyan** [windingwind/zotero-pdf-preview#9]
在信息窗口，预览中文论文基本上是逐段逐段渲染出来，英文论文就立刻渲染完整页。不知道是不是因为要渲染时要找字体所以很慢。

另外说句题外话，有些字体明明系统有，Zotero自带的pdf阅读器都不会渲染对应的中文字体，adobe和sumatraPDF是可以的。

**Comment by windingwind** [comment]
Zotero的阅读器，包括预览都是基于内部构建的pdf.js。pdf.js需要加载额外的cmap来支持非内置字体，例如中日韩等亚洲字符。关于渲染中文pdf慢的问题，参见https://github.com/mozilla/pdf.js/issues/7431
但这一问题似乎在firefox平台未见报告，因此我认为可能未必是中文慢，而是某些中文pdf由于格式不规范等各种原因而导致加载慢。
我测试了几个知网的学位论文，多数能够以正常速度（与英文pdf相比）渲染预览，少数pdf明显渲染时间更长。因此我感觉是pdf自身的问题。考虑到国内文献电子化的情况，是可能存在的。

关于字体：按照规范，作为正式文件的pdf应当在发布时嵌入字体以保证不同平台的显示一致性。此处也是由于pdf不规范导致的。部分本地阅读器可能会尝试加载系统字体，但pdf.js与他们的工作方式不同，似乎没必要为了少数情况而增加额外的工作量，我觉得zotero开发者也是这样考虑的。

**Comment by tangjyan** [comment]
是的知网的很多PDF都是不内置字体，然后下载知网阅读器的时候附带一大堆中文字体安装到系统中。

**Comment by windingwind** [comment]
是否有文档指出需要加载哪些额外字体？可以将这些字体作为额外可选项预载。

**Comment by tangjyan** [comment]
> 是否有文档指出需要加载哪些额外字体？可以将这些字体作为额外可选项预载。

我尝试过，万方在线出版的PDF基本把字体都压入了，而知网必须安装相应的字体才能正确显示。

由于中文期刊一般都是知网出版，所有需要加载的额外字体就是cnki阅读器自带的那些字体。
![image](https://user-images.githubusercontent.com/21167731/183015491-b54a4bbe-7ee5-4e1a-92fe-3e5af9c74c01.png)

**Comment by windingwind** [comment]
看起来需要的字体很多，会显著增大插件的体积，仅仅为了预览效果好像没有必要。

**Comment by tangjyan** [comment]
> 看起来需要的字体很多，会显著增大插件的体积，仅仅为了预览效果好像没有必要。

那顺带问一句，zotero自身的PDF阅读器有办法加载这些字体吗？比如说把字体放到什么文件夹下就可以了？

**Comment by windingwind** [comment]
![image](https://user-images.githubusercontent.com/33902321/183055200-1905a11d-e3de-4b28-a863-99ac729a6327.png)
在Zotero安装目录下zotero.jar（zipped file）resource->pdf-reader-cmaps，字体文件以bcmap格式存储。
理论上改了这里以后，对内置阅读器与预览都会生效。
