### ISSUE TITLE
无法安装插件“%S”。它可能无法与该版本的 Zotero 兼容。

### ISSUE THREAD

**Issue by youthcould** [windingwind/zotero-pdf-preview#91]
报告个bug

zotero 6.0.26
Win 11
安装最新版[Release 1.0.0-1](https://github.com/windingwind/zotero-pdf-preview/releases/tag/1.0.0-1)提示错误：
无法安装插件“%S”。它可能无法与该版本的 Zotero 兼容。
烦请修复

**Comment by windingwind** [comment]
Pre release is not for Zotero 6.
