### ISSUE TITLE
release Release 1.0.0-1 and 1.0.0-0 not working in windows 10, zotero 6.0.26

### ISSUE THREAD

**Issue by otaolafranc** [windingwind/zotero-pdf-preview#95]
Hello,
I tried to install the new releases of the pluging as the old one [Release 0.3.7] showed a blurry pdf preview. and I am getting the following error:
`The add-on "%S" could not be installed. It may be incompatible with this version of Zotero.`

**Comment by myradio** [comment]
Same here. With Zotero 6.0.26 on Windows 10 none of the versions 1.x.x are working with the same error described by @otaolafranc . Version 0.3.7 works.

**Comment by windingwind** [comment]
yes. They are only for zotero 7
