### ISSUE TITLE
Zotero 7 - Release 1.0.0-1 not working

### ISSUE THREAD

**Issue by yangzhangstl** [windingwind/zotero-pdf-preview#96]
I am having troubles to get the Release 1.0.0-1 to work with Zotero 7.0.0-beta.17+8017b2ab1 on macOS Ventura 13.4  Just after installation, the preview page is not shown anything. Thanks
<img width="990" alt="截屏2023-07-10 16 41 42" src="https://github.com/windingwind/zotero-pdf-preview/assets/88226594/72d4d600-8626-415f-8755-d89c26aa2a7b">
<img width="786" alt="截屏2023-07-10 16 42 11" src="https://github.com/windingwind/zotero-pdf-preview/assets/88226594/d19342a3-b44a-4b1e-9a60-4ec480f6986d">

**Comment by danieltomasz** [comment]
Plugin is working after restarting Zotero, but the info panel is resized, and half of its heights is replace by white place
![image](https://github.com/windingwind/zotero-pdf-preview/assets/7980381/1c90c08a-726a-4044-89fa-77b252f12445)

Zotero 7.0.0-beta.18+d7449b4d7
Plugin 1.0.0-1

**Comment by danieltomasz** [comment]
I can scroll and edit the info panel in this narrow space

**Comment by MeoCag** [comment]
same problem

**Comment by windingwind** [comment]
try 1.0.0-2
